# -*- coding: utf-8 -*-
"""TRABAJOFINALZAPAHOYOS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n9w4XaXNIBktH2NFOxlMaSF-ij6BFDu5
"""

menu = """

BIENVENIDO AL CINEMA WITCHERZH

1. REGISTRAR USUARIO
2. REGISTRAR RESERVA
3. CANCELAR RESERVA
4. CONSULTAR FUNCIONES FIN DE SEMANA
5. ADMINISTRADOR
6. SALIR

Cualquier otra opción cerrará el programa.

"""

menu2 = """

MENU ADMINISTRADOR

1. Total de reservas registradas
2. Total de tiquetes vendidos
3. Total de reservas realizadas
4. Total pago realizado
5. Promedio por venta diario del cine
6. Lista de usuarios
7. Usuario con mayor cantidad de reservas y menor cantidad de reservas.
8. Salir

Cualquier otra opción sale del menu.

"""

titulo = "CARTELERA CINEMA WITCHERZH"
titulo2 = "FUNCION DE ADMINISTRADOR"

dicVentas = {}

dicReportes = {}

adm = {
    "juan": "1068136988",
    "isaac": "1137974770"
}

tipo_vinculo = {
    "estudiante": 7500,
    "docente": 10000,
    "administrativo": 8500,
    "oficial interno": 7000,
    "publico externo": 15000
}

asientos = {
    'A': ["O","O","O","O","O","O","O","O","O","O","O"],
    'B': ["O","O","O","O","O","O","O","O","O","O","O"],
    'C': ["O","O","O","O","O","O","O","O","O","O","O"],
    'D': ["O","O","O","O","O","O","O","O","O","O","O"],
    'E': ["O","O","O","O","O","O","O","O","O","O","O"],
    'F': ["O","O","O","O","O","O","O","O","O","O","O"],
    'G': ["O","O","O","O","O","O","O","O","O","O","O"],
    'H': ["O","O","O","O","O","O","O","O","O","O","O"],
    'I': ["O","O","O","O","O","O","O","O","O","O","O"],
    'J': ["O","O","O","O","O","O","O","O","O","O","O"],
    'K': ["O","O","O","O","O","O","O","O","O","O","O"]
}

peliculas = [
        {"nombre": "AVENGERS: END GAME", "dia": "VIERNES", "hora": "20:00", "disponibles": 45},
        {"nombre": "SPIDER-MAN: NO WAY HOME", "dia": "SÁBADO", "hora": "15:00", "disponibles": 67},
        {"nombre": "THE BATMAN", "dia": "SÁBADO", "hora": "20:00", "disponibles": 23},
        {"nombre": "DUNE", "dia": "DOMINGO", "hora": "18:00", "disponibles": 89},
        {"nombre": "JOHN WICK 4", "dia": "DOMINGO", "hora": "21:00", "disponibles": 34}
    ]

import os


# CREAR BD CSV

def CrearBD_Usuarios():
    if not os.path.exists("usuarios.csv"):
        with open("usuarios.csv", "w", encoding="utf-8") as f:
            f.write("Documento,Nombre,Apellido,Vinculo\n")


def CrearBD_Reservas():
    if not os.path.exists("reservas.csv"):
        with open("reservas.csv", "w", encoding="utf-8") as f:
            f.write("Documento,Pelicula,Dia,Hora,Asiento,Precio\n")

# GUARDAR REGISTROS

def GuardarUsuario(cedula, nombre, apellido, vinculo):
    with open("usuarios.csv", "a", encoding="utf-8") as f:
        linea = f"{cedula},{nombre},{apellido},{vinculo}\n"
        f.write(linea)


def GuardarReserva(cedula, pelicula, dia, hora, asiento, precio):
    with open("reservas.csv", "a", encoding="utf-8") as f:
        linea = f"{cedula},{pelicula},{dia},{hora},{asiento},{precio}\n"
        f.write(linea)


while True:
    print(menu)
    opcion = input('Seleccione una opción: ')
    match opcion:
        case '1':
            nombre = input("Ingrese su nombre: ")
            if len(nombre) > 2:
                palabras = nombre.split()
                if all(palabra.isalpha() for palabra in palabras):
                    print("Nombre valido")
                else:
                    print("El nombre solo debe contener letras")
            else:
                print("El nombre solo debe llevar minimo 3 caracteres")
            # APELLIDO
            apellido = input("Ingrese su apellido: ")
            if len(apellido) > 2:
                palabras = apellido.split()
                if all(palabra.isalpha() for palabra in palabras):
                    print("Apellido valido")
                else:
                    print("El apellido solo debe contener letras")
            else:
                print("El nombre solo debe llevar minimo 3 caracteres")
            #DOCUMENTO
            cedula = input('Ingrese el número de documento: ')
            if len(cedula) < 3 and len(cedula) > 15:
                print("El apellido debe tener entre 3 y 15 caracteres")
            else:
                print("Documento registrado")

            # VINCULO
            vinculo = input("Ingrese su vinvulo (Estudiante, Docente, Administrativo, Oficiales internos, Publico externo): ")
            vinculo = vinculo.lower()
            if vinculo in tipo_vinculo.keys():
                pass
            else:
                print("Vinculo no valido, Ingrese uno que si este en la lista")

            #GUARDA EN DICCIONARIO
            dicVentas[cedula] = {
                    'nombre': nombre,
                    'apellido': apellido,
                    'vinculo': vinculo,
                    'reservas': []
                }
            print("Usuario registrado")

            GuardarUsuario(cedula, nombre, apellido, vinculo)

        case '2':
            print("REGISTRAR RESERVA")

            cedula = input("Ingrese su documento: ")

            # Verificar si el usuario está registrado
            if cedula not in dicVentas:
                print("Usuario no está registrado.")
                break

            # Mostrar cartelera
            print("\nCARTELERA:")
            for i, peli in enumerate(peliculas, start=1):
                print(i, "-", peli["nombre"], "|", peli["dia"], "|", peli["hora"], "| Disponibles:", peli["disponibles"])

            opcion_peli = int(input("Seleccione la película (número): "))

            if opcion_peli < 1 or opcion_peli > len(peliculas):
                print("Opción inválida.")
                break

            peli_seleccionada = peliculas[opcion_peli - 1]

            # Mostrar asientos simples
            print("\nASIENTOS:")
            print("    1 2 3 4 5 6 7 8 9 10 11")
            for fila, lista in asientos.items():
                print(fila, " ", " ".join(lista))

            asiento = input("\nSeleccione un asiento (ej: B2): ").upper()

            # mostrar fila y columna
            fila = asiento[0]
            col = int(asiento[1:]) - 1

            # confirmar asiento
            if fila not in asientos or col < 0 or col > 10:
                print("Asiento inválido.")
                break

            if asientos[fila][col] == "X":
                print("Ese asiento ya está ocupado.")
                break

            # Reservar asiento
            asientos[fila][col] = "X"
            peli_seleccionada["disponibles"] -= 1

            precio = tipo_vinculo[dicVentas[cedula]["vinculo"]]

            # Guardar reserva sencilla
            dicVentas[cedula]["reservas"].append({
                "pelicula": peli_seleccionada["nombre"],
                "dia": peli_seleccionada["dia"],
                "hora": peli_seleccionada["hora"],
                "asiento": asiento,
                "precio": precio
            })
            GuardarReserva(
    cedula,
    peli_seleccionada["nombre"],
    peli_seleccionada["dia"],
    peli_seleccionada["hora"],
    asiento,
    precio
)
            # Mostrar factura
            print(" RESERVA REGISTRADA ")
            print("Usuario:", dicVentas[cedula]["nombre"], dicVentas[cedula]["apellido"])
            print("Película:", peli_seleccionada["nombre"])
            print("Día:", peli_seleccionada["dia"])
            print("Hora:", peli_seleccionada["hora"])
            print("Asiento:", asiento)
            print("Valor pagado:", precio)

            print("Reserva completada.")

#caso 3

        case "3":
            print(titulo.center(80))
            print("\n CANCELAR RESERVA ")

            cedula = input("Ingrese su documento: ")

            # Verificar que el usuario exista
            if cedula not in dicVentas:
                print("Usuario no esta registrado")
                break

            # Verificar que tenga reservas
            if len(dicVentas[cedula]["reservas"]) == 0:
                print("El usuario no tiene reservas activas.")
                break

            # Mostrar reservas
            print("\nReservas del usuario:")
            for i, reserva in enumerate(dicVentas[cedula]["reservas"], start=1):
                print(i, "-", reserva["pelicula"], "|", reserva["dia"], "|", reserva["hora"], "| Asiento:", reserva["asiento"])

            seleccion = int(input("Seleccione el número de la reserva a cancelar: "))

            if seleccion < 1 or seleccion > len(dicVentas[cedula]["reservas"]):
                print("Opción inválida.")
                break

            reserva = dicVentas[cedula]["reservas"][seleccion - 1]
            asiento = reserva["asiento"]

            # Devolver el asiento a "O"
            fila = asiento[0]
            col = int(asiento[1:]) - 1
            asientos[fila][col] = "O"

            # Devolver disponibilidad a la película
            for peli in peliculas:
                if peli["nombre"] == reserva["pelicula"]:
                    peli["disponibles"] += 1
                    break

            # Eliminar la reserva
            dicVentas[cedula]["reservas"].pop(seleccion - 1)

            print("\nReserva cancelada correctamente.\n")

#caso 4

        case "4":
            print("\n--- FUNCIONES DEL FIN DE SEMANA ---\n")

            print("Día       | Hora   | Película                       | Disponibles")
            print("="*80)

            for peli in peliculas:
                print(peli["dia"].ljust(10), "|",
                      peli["hora"].ljust(7), "|",
                      peli["nombre"].ljust(30), "|",
                      peli["disponibles"])

            print("\nRegresando al menú...\n")

#caso 5
        case "5":
            print(titulo2.center(80))
            nombre = input("Ingrese nombre: ").lower()
            if nombre in adm:
                documento = input("Ingrese documento: ")
                if adm[nombre] == documento:
                    print(f"Bienvenido {nombre}")
                else:
                    print("Documento incorrecto")
            else:
                print("Nombre de administrador no encontrado")

            while True:
                print(menu2)
                opcion = input('Seleccione una opción: ')
                match opcion:
                    case '1':
                        total_reservas = 0
                        for cedula in dicVentas.keys():
                            total_reservas += len(dicVentas[cedula]['reservas'])
                        print(f"Total: {total_reservas}")

                        print(f"TOTAL DE RESERVAS REGISTRADAS: {total_reservas}")
                    case '2':
                        total_reservas = 0
                        for cedula in dicVentas.keys():
                            total_reservas += len(dicVentas[cedula]['reservas'])
                        print(f"Total: {total_reservas}")

                        print(f"TOTAL DE TIQUETES VENDIDOS: {total_reservas}")
                    case '3':
                        total_reservas = 0
                        for cedula in dicVentas.keys():
                            total_reservas += len(dicVentas[cedula]['reservas'])
                        print(f"Total: {total_reservas}")

                        print(f"TOTAL DE RESERVAS REALIZADAS: {total_reservas}")
                    case '4':
                            print("TOTAL PAGO REALIZADO")
                            total_pagado = 0
                            for cedula in dicVentas:
                                for reserva in dicVentas[cedula]["reservas"]:
                                    total_pagado += reserva["precio"]
                            print(f"El total pagado es: ${total_pagado}")

                    case '5':
                            total_pagado = 0
                            for cedula in dicVentas:
                                for reserva in dicVentas[cedula]["reservas"]:
                                    total_pagado += reserva["precio"]

                            if total_pagado == 0:
                                print("No se han registrado ventas aún.")
                                break
                            else:
                                pass
                            promedio_diario = total_pagado / 3
                            print(f"Promedio de ventas diario es ${promedio_diario:.2f}")
                    case '6':
                            print("\LISTA DE USUARIOS")
                            print("Documento | Nombre | Apellido | Vinculo | Reservas")
                            print("="*80)
                            for cedula, datos in dicVentas.items():
                                nombre = datos["nombre"]
                                apellido = datos["apellido"]
                                vinculo = datos["vinculo"]
                                reservas = len(datos["reservas"])

                                print(f"{cedula} | {nombre} | {apellido} | {vinculo} | {reservas}")
                    case '7':
                            print("USUARIO CON MAYOR Y MENOR CANTIDAD RESERVAS")
                    case _:
                        print("Acaba de salir del menu administrador")
                        break

        case _:
            print('Gracias por usar el Cine THEWITCHERZH. Hasta pronto')
            break

from google.colab import drive
drive.mount('/content/drive')